- menu_name: "Contents"

- name: "Modules"
  url: "/modules/"
  title: "Modules"

- name: "Exercises"
  url: "/exercises/"
  title: "Exercises"

- name: "Resources"
  url: "/resources/"
  title: "Resources"
